### PR TITLE
nginx ≥1.11 compatibility

### PR DESCRIPTION
**Pull request by manwe-pl**

### CODE REVIEW

**Comment by msva** [comment]
by the way, can you remind me, why do stream module isn't suitable in case where you're using this (tcp proxy) module (which codebase, to be honest, looks kinda outdate)?

**Comment by manwe-pl** [comment]
Here's the original code: https://github.com/yaoweibin/nginx_tcp_proxy_module 

AFAIK stream module in free version of nginx doesn't support things like type=mysql/smtp/pop3/imap/ssl_hello or tcp_check_status; directives.

**Comment by msva** [comment]
that things looks like the business of some kind of stream_upstream_check, but not stream module itself.
And this is also a part of another submodule in tcp-proxy module, called, `ngx_tcp_upstream_module`.

And, it looks like most part of that module is copied from https://github.com/yaoweibin/nginx_upstream_check_module.
Although, original one missing mail (imap,pop3,smtp) `type`s.

So, actually, right way will be to take them both and split to 3 modules:
`http_upstream_check`, `mail_upstream_check` and `stream_upstream_check` (last one should also support udp, by the way).

Maybe someday I'll find a time to do that, but, unfortunatelly, not now.

And, is it (health check with mail features) the **only** reason for you to prefer that module over stream?

**Comment by manwe-pl** [comment]
I'm using it for reverse mysql proxy + zabbix is monitoing tcp_check_status; (which I've changed from HTML to JSON). One day, when I have free time (yeah, right…) I might try upstream_*, but for now tcp is doing it's job and those few incompatibilities where easy to fix.

**Pull request merged**
